spring:
  cloud:
    gateway:
      routes:
        - id: adventurer-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/adventurers/**
          filters:
            - StripPrefix=1
        - id: quest-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/quests/**
          filters:
            - StripPrefix=1
        - id: matching-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/match/**
          filters:
            - StripPrefix=1
